# サイト基本情報
title: 中根進之介ポートフォリオ
email: your.email@example.com
description: 中根進之介のデータ分析、IoT、ゲーム開発に関するポートフォリオサイト
url: "https://shin-nakane.github.io" # ご指定のURL
baseurl: "/biogeoworld" # ユーザーページなので空でOK

# Jekyllの設定
markdown: kramdown
theme: minima # Jekyllの動作に必要な基本設定を補完
plugins:
  - jekyll-feed
  - jekyll-sitemap
 
# Google Search Console
google_site_verification: "t53rD3NblQJyC2ZrIp0LezMwtM5Zn16gG_36R0lrRDA"